### ISSUE TITLE
signing error

### ISSUE THREAD

**Issue by astutesoftware** [diawi/knowledge-base#1]
Getting the following error since today.
4001504: Invalid .apk file: couldn't retrieve the signature, the app must be signed to be able to install it on a device

Earlier same apk used to work, but now it is showing these errors for all apk's uploaded.
I usually upload the debug version

**Comment by GregOriol** [comment]
Hi @astutesoftware,

Thanks for your message. However, this is not the right place to open a specific issue: this knowledge base is a general set of information about Diawi and app uploads.
For your specific issue, please check the Diawi website for support choices.

Best regards,
