### ISSUE TITLE
Error while upload the IPA

### ISSUE THREAD

**Issue by Balaprabustar** [diawi/knowledge-base#2]
Dear Team, 
I used diawi to upload the ipa and circulated the link to download the app. For the past 2 weeks i'm receiving below error.
<img width="410" alt="screen shot 2018-11-30 at 3 16 28 pm" src="https://user-images.githubusercontent.com/19779471/49281592-f49bb000-f4b2-11e8-9c67-bdc3e7d111e6.png">

When we debug in the developer console, we received ERR_SSL_VERSION_INTERFERENCE or CROS Error.
I tried with various network option and different browser, still same error persist.

**Comment by GregOriol** [comment]
Hi @Balaprabustar ,

Thanks for your message. However, this is not the right place to open a specific issue: this knowledge base is a general set of information about Diawi and app uploads.
For your specific issue, please check the Diawi website for support choices.

Best regards,
