### ISSUE TITLE
Does m.diawi.com work?

### ISSUE THREAD

**Issue by AlexanderMatveev** [diawi/knowledge-base#3]
https://github.com/diawi/knowledge-base/blob/master/iOS/Cant-install-an-app-on-a-device-things-to-check.md#valid-udids says:

> Device's UDID must be retrieved using iTunes or a webapp like m.diawi.com: those UDIDs are known to be valid.

But looks like m.diawi.com is down. Does this mean there is no way to get UDID from any website?

**Comment by GregOriol** [comment]
@AlexanderMatveev Indeed, `m.diawi.com` was an old address that we don't use anymore. Currently, our webapp can be access at the address: https://webapp.diawi.com

**Comment by GregOriol** [comment]
The docs have been fixed! Thanks

**Comment by AlexanderMatveev** [comment]
@GregOriol thanks!
